version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app3.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
