services:
  - type: web
    name: strong-stock-scanner
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_APP
        value: app3.py
      - key: PYTHONUNBUFFERED
        value: 1
    plan: free
