services:
  - type: web
    name: pitk1
    env: docker
    dockerCommand: docker build -t pitk1 . && docker run -p 10000:5000 pitk1
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONIOENCODING
        value: "utf-8"
      - key: FLASK_APP
        value: app3.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    plan: free
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true
