services:
  - type: web
    name: pitk1
    env: python
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: gunicorn app3:app
    python:
      version: 3.10.13
    envVars:
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONIOENCODING
        value: "utf-8"
      - key: FLASK_APP
        value: app3.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: PYTHON_VERSION
        value: "3.10"
    plan: free
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true
